# Generated by Django 2.1.7 on 2019-03-27 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_user_info_user_pw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_id',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='user_id',
            field=models.CharField(max_length=9, primary_key=True, serialize=False),
        ),
    ]
