# Generated by Django 2.1.7 on 2019-04-04 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_auto_20190404_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='overdue',
            field=models.DateTimeField(default=0),
        ),
    ]
