# Generated by Django 2.1.7 on 2019-05-17 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_auto_20190517_2013'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Borrow',
            new_name='Borrow_list',
        ),
    ]
