# Generated by Django 2.1.7 on 2019-06-04 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_auto_20190517_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_id',
            field=models.CharField(max_length=11, primary_key=True, serialize=False),
        ),
    ]
