# Generated by Django 2.1.7 on 2019-06-04 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_auto_20190604_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_id',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
    ]
