# Generated by Django 2.1.7 on 2019-08-07 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_auto_20190604_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
